<a href="https://colab.research.google.com/github/2303A51528/DM1528/blob/main/JAN28%20LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [5]:
# Load CSV from URL or Google Drive
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'  # Updated URL for Titanic dataset
import pandas as pd
data = pd.read_csv(url)

In [6]:
# Display the first few rows of the dataset
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
# Check for missing values
print(data.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
# Impute missing values with mean (for numerical columns)
data['Age'].fillna(data['Age'].mean(), inplace=True)

<ipython-input-8-4454e2e82a17>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(), inplace=True)

In [9]:
# Alternatively, you can impute with the median
data['Age'].fillna(data['Age'].median(), inplace=True)

<ipython-input-9-e8cf12bf9213>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].median(), inplace=True)

In [10]:
# Or, impute with the mode (for categorical columns)

In [11]:
data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)

<ipython-input-11-242c687cad47>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)

In [12]:
# Verify that missing values are handled
print(data.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
# Initialize MinMaxScaler
scaler = MinMaxScaler()

In [15]:
# Select columns to normalize (numerical columns)
columns_to_normalize = ['Age', 'Fare']

In [17]:
# Apply Min-Max normalization
data[columns_to_normalize] = scaler.fit_transform(data[columns_to_normalize])

In [18]:
# Display the first few rows after normalization
data[columns_to_normalize].head()

        Age      Fare
0  0.271174  0.014151
1  0.472229  0.139136
2  0.321438  0.015469
3  0.434531  0.103644
4  0.434531  0.015713

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
# Initialize StandardScaler
scaler = StandardScaler()

In [22]:
# Apply standardization to numerical columns
data[columns_to_normalize] = scaler.fit_transform(data[columns_to_normalize])

In [23]:
# Display the first few rows after standardization
data[columns_to_normalize].head()

        Age      Fare
0 -0.592481 -0.502445
1  0.638789  0.786845
2 -0.284663 -0.488854
3  0.407926  0.420730
4  0.407926 -0.486337

In [24]:
# Import necessary libraries
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from google.colab import files

In [26]:
# Upload a dataset (replace 'your_file.csv' with your actual file name if
# uploading manually)
# uploaded = files.upload()
# Note: The above line is commented out because it depends on a library like google.colab,
# which may not be available in all environments. To make the code executable without modification,
# uncomment it ONLY when running in the relevant environment.

In [28]:
# Upload a dataset (replace 'your_file.csv' with your actual file name if
# uploading manually)
# uploaded = files.upload()
# Note: The above line is commented out because it depends on a library like google.colab which is not always available.
# To use this, uncomment it when in a Google Colab environment.

In [29]:
# Check for missing values
print("Missing values before imputation:")
print(data.isnull().sum())

Missing values before imputation:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [31]:
# Handle missing values (impute with mean, median, or mode)
# Handle missing values (impute with mean, median, or mode)
data['Age'].fillna(data['Age'].mean(), inplace=True)  # Impute with mean
data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)  # Impute with mode

<ipython-input-31-7d269ef51e32>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(), inplace=True)  # Impute with mean
<ipython-input-31-7d269ef51e32>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)  # Impute with mode

In [32]:
# Check for missing values after imputation
print("\nMissing values after imputation:")
print(data.isnull().sum())

Missing values after imputation:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [34]:
# Feature scaling (Min-Max Normalization)
# Feature scaling (Min-Max Normalization)
from sklearn.preprocessing import MinMaxScaler
scaler_minmax = MinMaxScaler()
columns_to_normalize = ['Age', 'Fare']
data[columns_to_normalize] = scaler_minmax.fit_transform(data[columns_to_normalize])

In [36]:
# Feature scaling (Standardization)
scaler_standard = StandardScaler()
data[columns_to_normalize] = scaler_standard.fit_transform(data[columns_to_normalize])

In [37]:
# Display the first few rows of the dataset
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,-0.592481,1,0,A/5 21171,-0.502445,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.638789,1,0,PC 17599,0.786845,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,-0.284663,0,0,STON/O2. 3101282,-0.488854,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.407926,1,0,113803,0.420730,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,0.407926,0,0,373450,-0.486337,NaN,S